"""empty message

Revision ID: 629c554297ac
Revises: 3f4a9f8cfc85
Create Date: 2024-06-11 19:43:39.513018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '629c554297ac'
down_revision = '3f4a9f8cfc85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seen_walkthrough', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('seen_walkthrough')

    # ### end Alembic commands ###
