"""empty message

Revision ID: 361870288f6d
Revises: 3bb76a53e474
Create Date: 2024-05-21 10:33:39.472273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '361870288f6d'
down_revision = '3bb76a53e474'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friends_expenses', schema=None) as batch_op:
        batch_op.alter_column('expense_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friends_expenses', schema=None) as batch_op:
        batch_op.alter_column('expense_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    # ### end Alembic commands ###
