"""update times testing

Revision ID: 760ebb791739
Revises: cf1cadc89c06
Create Date: 2024-05-19 18:05:26.041484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '760ebb791739'
down_revision = 'cf1cadc89c06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friends_expenses', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
        batch_op.alter_column('expense_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friends_expenses', schema=None) as batch_op:
        batch_op.alter_column('expense_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)

    # ### end Alembic commands ###
